app:
  env: "local"
  port: "8086"
  version: "1.0.0"

auth:
  jwt_pub: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvys7X2EIsWAO2T5mgTj6
    vI3gCRYHb8rMkkJvzf6Gq57DLAsDcYKtbnBF5To716rb3S/aAVWWnmXABMpIqlIk
    GxoXIAkKa6yrPl2jHgcAxoNTTO28M4g8QSjsYJQe2RsbgAr+s24HGnsCYeUGSiR7
    J53h3fteqWsZBQSR3r7E3BiM+nclx7ICvtegV2lhnRGKp1MoZblYRbBikHiEA/8T
    YyMgo6d394BBsiRFHNA89ykkPX/Zz0e07Tryi1ZX60Y8LnlL7oI8Xtx6naEkmvWj
    AwZrrMWq4zmpCS5QydGZ2kS3EKpXe5ZTN/zKZv1vmB1AcpVtKhIY5r+/b0PMIU0/
    0QIDAQAB
    -----END PUBLIC KEY-----

recaptcha:
  host: "https://www.google.com/recaptcha/api/siteverify"
  secret: ""

db:
  url: "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable&search_path=public"

cache:
  url: "redis://:1020304050@localhost:6379/0"

broker:
  # kafka_protocol://kafka_username:kafka_password@kafka_host:kafka_port/kafka_partition
  url: "kafka://:@localhost:9092/0"
  # topic for kafka producer
  consumer_group: "bb.consumer.dev.boilerplate"
  consumer_topic_prefix: "bb.topic.dev.boilerplatesvc"
  topic_to_consume: "echo"
  producer_dead_letter_prefix: "bb.topic.dl.dev"

nats:
  url: "nats://:@localhost:4222"
  responder_group: "bb.responder.dev.boilerplate"

cdn:
  url: "s3://access_key:secret_key@localhost:9000/region"
  bucket: "bucket_name"

promprobe:
  username: "admin"
  password: "admin"
